cs01/gdbgui

setup.py
The default encoding of `open` on Windows (Chinese Simplified) is "GBK", which will cause an `UnicodeDecodeError` when `open('README.rst', 'r').read()`
=> Add explicit `encoding = "utf-8"` for `open`

gdbgui/backend.py
Fixes:
```python
NameError: global name 'STARTUP_WITH_SHELL_OFF' is not defined
```
=> Fixes 'STARTUP_WITH_SHELL_OFF' is not defined

gdbgui/static/js/gdbgui.js
I think this should work.
Can't perform `-var-set-update-range <varname> 0 <new_num_children>` because `new_num_children` isn't present in `changelist` in this situation, but only 'has_more'.
Also, `-var-set-update-range <varname> 0 <new_num_children>` with `new_num_children` specified by hand doesn't work either. Not sure why.
But `Expressions._get_children_for_var` (aka. `-var- list-children`) seems working.
=> BUG FIX: container `empty -> 1 element` bug fix

README.rst
You may not want to pull this request to avoid cluttering the README too much but I spent a day figuring out why gdbgui couldn't detect gdb. I realized at the end that gdbgui cannot be compiled using MinGW and python installed outside of cygwin so this may help a developer somewhere.
=> Added required cygwin packages to README.rst

README.rst
This PR is kind of pedantic.
FreeBSD != "Free BSD". (https://www.freebsdfoundation.org/about/project/). The additional trailing slash in a couple URLs are unnecessary as well.
=> README.rst: fix FreeBSD's name and remove unnecessary trailing slashes from URLS

gdbgui/src/js/GdbApi.jsx
Remove hard-coded http protocol so it can work on https via reverse proxy. 
(Mixing http and https is not allowed in some browsers.) 
Using /gdb_listener works for me... but you could also use the document.protocol instead of http.
=> change socket to relative path

gdbgui/backend.py
Here is a patch which does what I think is reasonable: causes --args to take all remaining arguments as program arguments as with 'gdb --args'. The 'cmd' argument only takes the program name now. There are three options for 'cmd':
1. Leave 'cmd' as nargs='*'; then any flags passed as '-' are ambiguous with gdbgui arguments unless the entire command string is qutoed, in which case it might as well be nargs=1. (i.e. `gdbgui [gdbgui-args] cmd [these-are-more-gdbgui-args]`)
1. Set 'cmd' as nargs=1; this essentially works the same as above, but shows this explicitly in the usage string. Then to pass a full command string you would either do `gdgbui 'quoted-command --with-arguments' [gdbgui-args...]`.
1. Set 'cmd' as nargs=`argparse.REMAINDER`; in this case the first non-option argument would …
=> Issue #194: Change --args to match 'gdb --args'. 'cmd' now only takes program name.

gdbgui/backend.py
Support for -b/--browser to override default browser executable. Mutually exclusive with -n/--no-browser.
=> Feature #199: Add -b/--browser argument to specify browser executable

gdbgui/src/js/Breakpoints.jsx
Display the breakpoint's 'times' field when the 'Breakpoint' component is rendered. Do not display a hit count if the breakpoint is a child breakpoint or if the breakpoint has never been hit.
Here's a screenshot of the modified breakpoint component: 
Closes #187
=> WIP: Show number of times breakpoint was hit

gdbgui/statemanager.py, noxfile.py, tests/test_main.py
To debug an application+command line arguments "--args" is used as last command line argument of gdbgui. Everything after "--args" must be passed then to gdb also as LAST command line argument.
This was not the case, but it is now ensured. By default gdb is now used in any case with "--args".
- I tested the code with gdb 8.3
- I removed the deepcopy() as it is IMHO not required.
=> Ensure "--args" is last argument of gdb command

docs/installation.md
=> Docs: Installation - Reset your console after userpath append

docs/contributing.md, make_executable.py, noxfile.py, setup.py
This commit has several bug fixes. Building on MacOS is broken by default without these changes:
- Add required python packages that were missing from setup.py; a clean computer install would throw an exception due to missing packages. 
- Add hiddenimports for pyinstaller, so that pyinstaller properly loads gevent
- Modify noxfile so that it loads the required packages when creating a session. Also, python 3.7 support was added in pyinstaller 3.4, so pyinstaller version needs to be updated.
=> Bugfixes for building executable

docker/windows/Dockerfile, gdbgui/src/js/Registers.jsx, gdbgui/src/js/process_gdb_response.js, setup.py
Not sure how these made it past CI, but hopefully we can avoid regressions like this in the future
=> lint fixes

docs/examples.md
- [] I have added an entry to `docs/changelog.md`
(**I have not, since it is a minor documentation fix, but if it requires an entry to changelog, please let me know**)
The documentation in https://www.gdbgui.com/examples/ for `rr replay` causes an issue as it currently stands. In particular, the command provided `gdbgui --gdb-cmd "rr replay"` causes things to error our and quit instantly. The command should be updated to `gdbgui --gdb-cmd "rr replay --"` so that the extra arguments that gdbgui adds regarding new ui and such are passed along correctly to `gdb`.
Tested by running
```
gdbgui --gdb-cmd "rr replay"
gdbgui --gdb-cmd "rr replay --"
```
=> Fix documentation for opening `rr replay`

setup.py
**I defer to the @cs01 about what to add to the changelog here**
Issue https://github.com/cs01/gdbgui/issues/366
`python-socketio` released a new version that points to the new SocketIO v3. This is a major protocol update making v2 and v3 incompatible:
https://socket.io/docs/v3/migrating-from-2-x-to-3-0
> TL;DR: due to several breaking changes, a v2 client will not be able to connect to a v3 server (and vice versa)
This PR pins the server to use `>=4.6.1` of `python-socketio` which uses the v2 protocol, the same as what the client uses.
You can see a table that details the `python-socketio` version breakdown [here](https://pypi.org/project/python-socketio/).
N/A
=> fixes client using unsupported version of Socket.IO protocols

CHANGELOG.md
This is a followup to PR #362.
- - -
I got confused first, as I only reviewed the changelog after my usual `--rr` stopped working.
=> fix changelog entry for --rr

gdbgui/server/sessionmanager.py
Disable pagination on gdb startup. Otherwise the GUI can't accept commands while gdb is waiting for the user to press enter to continue. Also since the gdb window has scrollbars pagination seems pointless.
Test suite run successfully.
You can see the difference with a command like _gdbgui -g '/usr/bin/gdb -ex "help breakpoints"'_
=> Disable pagination on gdb startup

docs/guides.md
gdb supports omitting IP address for cases when it's a "wait for
connection from anywhere". Make use of it to simplify the call.
Not needed *(documentation change)*.
=> guides.md: simplify gdbserver call

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, MANIFEST.in, gdbgui/server/app.py, gdbgui/src/js/InitialStoreData.ts, gdbgui/src/js/TopBar.tsx
- Display gdbgui version in "about" and "session information"
Tested by running
```
> yarn start
> nox -s serve
```
=> show gdbgui version in more places

.github/workflows/build_executable.yml, CHANGELOG.md, docs/index.md, make_executable.py, noxfile.py
- Build gdbgui as a [pex](https://pypi.org/project/pex/) executable.
- These are executable Python environments that are self-contained with the exception of requiring a specific Python version installed in the environment running the executable. The pex executables should have better compatibility than PyInstaller executables, which sometimes have missing shared libraries depending on the operating system.
- Included in github action, as well as a nox session  
Tested by running
```
> nox -s build_pex
~/git/gdbgui/build/pex csmith@gram (cs01/add-pex*)
> md5sum gdbgui.pex
bb65703f2aa5dfef60a2b475a8341d69  gdbgui.pex
~/git/gdbgui/build/pex csmith@gram (cs01/add-pex*)
> cat gdbgui.pex.md5 
bb65703f2aa5dfef60a2b475a8341d69
> ./build/pex/gdbgui.pex
```
=> build gdbgui as python executable (pex)

docs/api.md
- [] I have added an entry to `CHANGELOG.md`, or an entry is not needed for this change
* Updated API page of the website with the current help screen
=> Updated help page (`--rr` does not exist anymore)

noxfile.py
- [] I have added an entry to `CHANGELOG.md`, or an entry is not needed for this change
No changelog entry needed
Pin version of black to avoid error
```
Traceback (most recent call last):
File "/home/runner/work/gdbgui/gdbgui/.nox/lint/bin/black", line 5, in <module>
from black import patched_main
File "/home/runner/work/gdbgui/gdbgui/.nox/lint/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
from typed_ast import ast3, ast27
File "/home/runner/work/gdbgui/gdbgui/.nox/lint/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
from typed_ast import _ast3
ImportError: /home/runner/work/gdbgui/gdbgui/.nox/lint/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
```
See …
=> bump pinned version of black

gdbgui/server/ptylib.py
- [] I have added an entry to `CHANGELOG.md`, or an entry is not needed for this change
This PR implements a fix suggested in https://github.com/cs01/gdbgui/issues/407.
There are also other UTF-8 issues that might be related to this:
https://github.com/cs01/gdbgui/issues/130
https://github.com/cs01/gdbgui/issues/347
https://github.com/cs01/gdbgui/issues/292
Tested by running
```
```
=> Do not crash on UTF-8 decode errors

.flake8, noxfile.py, requirements.txt
- this should be done by the package maintainer, when a new version is released
- some of the problems are introduced by fixed requirements introduced in version 0.15.1.0
- build will run successfully with python3.11
- tested on linux (`nox -s build_executables_current_platform`)
- develop mode is working `nox -s develop`
- fix #447 
- this will bump some the versions of some requirements
- update the noxfile to support python 3.11
- fix the flake8 config file: comments should start in an extra line
Tested by running `nox`
```
nox > * tests-3.11: success
nox > * lint: failed
nox > * docs: success
nox > * cover: success
```
One of the linting errors is also handled with this PR. This change/PR has nothing to do with failed lint tests. They should be handled separately.
What failed?
- some …
=> Support Python 3.11 - Fix 447
